### PR TITLE
CI: Python build

### PR DESCRIPTION
**Pull request by ZhymabekRoman**
Thanks for this project! This PR automates python package builds and PyPI uploads, enhancing release efficiency.

### CODE REVIEW

**Comment by davidandreoletti** [comment]
@phiresky Hi, This PR is important  for this project to reach a wider python dev base and save 10s of GiB for a project I am personably working on.

Would you mind looking into/merge it ?

@ZhymabekRoman Thank you for this PR!!

**Comment by phiresky** [comment]
I can merge this but I guess for pypi uploads I'd need to create an account / org there first?

**Comment by ZhymabekRoman** [comment]
> 10s of GiB for a project I am personably working on.

Yeah, it's so true.

> I can merge this but I guess for pypi uploads I'd need to create an account / org there first?

Yes, you need to create a PyPI account

**Comment by phiresky** [comment]
@ZhymabekRoman  it doesn't seem to work, see https://github.com/phiresky/sqlite-zstd/actions/runs/8986213863/job/24681790073

**Comment by ZhymabekRoman** [comment]
@phiresky #39 Should fix the problem

**Pull request merged**
